### ISSUE TITLE
смогла ручками, не смогла ботиком

### ISSUE THREAD

**Issue by nimfadore** [Kwentar/telegram_bots#2]
nickname:  panovivan

нашла почту: i.panov@bars-open.ru

**Comment by Kwentar** [comment]
У него имя того, кто коммитит не совпадает с аккаунтом (аккаунт PanovIvan, а автор коммита Панов Иван), теперь добавил что если ничего не найдет, то будет выдавать что-нибудь с пометкой "Probably"

**Comment by nimfadore** [comment]
ок))
